// Generated by https://quicktype.io

export interface Data {
  id: string;
  name: string;
  bn_name: string;
  lat: string;
  long: string;
  districts?: Data[];
  subdistricts?: Data[];
  icon?: string;
}
